name: search_repo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  freezed_annotation:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod:
  http: ^1.1.0
  riverpod_annotation: ^2.1.2
  intl:
  lottie:
  hooks_riverpod: ^2.3.8
  device_preview:
  go_router:
  shared_preferences:
  tuple:
dev_dependencies:
  freezed:
  build_runner: ^2.4.6
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_generator:
  envied_generator:
  mockito: ^5.4.2


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
