name: search_repo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  device_preview:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  flutter_hooks:
  freezed_annotation:
  go_router:
  hooks_riverpod: ^2.3.8
  http: ^1.1.0
  intl:
  lottie:
  riverpod_annotation: ^2.1.2
  shared_preferences:
  tuple:
  url_launcher:


dev_dependencies:
  build_runner: ^2.4.6
  envied_generator:
  flutter_driver:
    sdk: flutter
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  lint:
  mockito: ^5.4.2
  riverpod_generator:




flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/