name: search_repo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  freezed_annotation:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod:
  http:
  riverpod_annotation: ^2.1.2
  intl:
  lottie:
  hooks_riverpod: ^2.3.8
  device_preview:
  go_router:
  shared_preferences:

dev_dependencies:
  freezed:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_generator:
  envied_generator:
  mockito:


flutter:
  uses-material-design: true

